[2024-11-05 18:00:03,903][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:00:03,904][root][INFO] - Env:
CUDA_VISIBLE_DEVICES: null
PYTHONOPTIMIZE: null

[2024-11-05 18:00:03,904][root][INFO] - Command line args:

[2024-11-05 18:00:03,904][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:00:03,906][root][INFO] - Run config:
device: cuda:4
solver_fn: nk.optimizer.solver.cholesky
lr: 0.0001
diag_shift: 1.0e-10
n_iter: 2000
chunk_size_jac: 2
chunk_size_vmap: 1
save_every: 3
base_dir: /scratch/.amisery/grad_sample/
model:
  _target_: grad_sample.model.ising.TFI
  L: 3
  h: 1.0
ansatz:
  _target_: nk.models.RBM
  alpha: 1
task:
  _target_: grad_sample.tasks.fullsum_train.Trainer

[2024-11-05 18:00:03,907][root][INFO] - ---------------------------------------------------------------
[2024-11-05 18:00:06,398][root][CRITICAL] - Error in call to target 'grad_sample.tasks.fullsum_train.Trainer':
InstantiationException("Error locating target 'grad_sample.model.ising.TFI', set env var HYDRA_FULL_ERROR=1 to see chained exception.\nfull_key: model")
full_key: task
Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'grad_sample' has no attribute 'model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'grad_sample.model'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'grad_sample.model.ising.TFI':
ModuleNotFoundError("No module named 'grad_sample.model'")
Are you sure that 'model' is importable from module 'grad_sample'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/fullsum_train.py", line 16, in __init__
    super().__init__(cfg)
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/tasks/base.py", line 21, in __init__
    self.model = instantiate(self.cfg.model)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'grad_sample.model.ising.TFI', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amisery/phd/tfi_gs_samples/grad_sample/src/grad_sample/main.py", line 49, in main
    task = instantiate(cfg.task, cfg)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
  File "/scratch/.amisery/netket2/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'grad_sample.tasks.fullsum_train.Trainer':
InstantiationException("Error locating target 'grad_sample.model.ising.TFI', set env var HYDRA_FULL_ERROR=1 to see chained exception.\nfull_key: model")
full_key: task
